spring:
  datasource:
    url: jdbc:h2:mem:usersDb;NON_KEYWORDS=user
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate.ddl-auto: none
    show-sql: false
  h2:
    console.enabled: true
    console.path: /h2
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
