INSERT INTO "USER" (LOGIN,PASSWORD,CLIENTE,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,EMAIL,NO_ACCESO,AREA)
VALUES('test','$2a$10$YB/v48VOvuwlNZ.eE4vfSuLw3d38jGLUvYVq/3oHdSRTOfhZtWbS.','123456','Juan','Perez','Alvarez','jperez@gmail.com',1,1);
INSERT INTO "USER" (LOGIN,PASSWORD,CLIENTE,NOMBRE,APELLIDO_PATERNO,APELLIDO_MATERNO,EMAIL,NO_ACCESO,AREA)
VALUES('test2','$2a$10$YB/v48VOvuwlNZ.eE4vfSuLw3d38jGLUvYVq/3oHdSRTOfhZtWbS.','123457','Miguel','Lopez','Jimenez','jperez@gmail.com',1,1);